name: Automacao

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Install Chrome
        run: |
          choco install googlechrome -y
          choco install chromedriver -y

      - name: Build with Maven
        env:
          GH_TOKEN: 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
        run: |
          mvn clean test -Dgithub.token=$GH_TOKEN

      - name: Generate Allure Report
        run: mvn allure:report

      - name: Publish Allure Results
        uses: allure-actions/upload@v2
        with:
          resultsDirectory: allure-results

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/site/allure-maven-plugin

      - name: Cleanup
        run: mvn clean
